-- RentFlow Sprint 1 schema.
-- Run this in Supabase SQL Editor before testing the new Sprint 1 screens.

alter table public.bookings
  add column if not exists status text not null default 'pending',
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancelled_by uuid references auth.users(id);

alter table public.users
  add column if not exists expo_push_token text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'bookings_status_check'
  ) then
    alter table public.bookings
      add constraint bookings_status_check
      check (status in ('pending', 'accepted', 'rejected', 'cancelled', 'completed'));
  end if;
end $$;

do $$
declare
  apartment_id_type text;
  booking_id_type text;
begin
  select format_type(attribute.atttypid, attribute.atttypmod)
  into apartment_id_type
  from pg_attribute attribute
  join pg_class class on class.oid = attribute.attrelid
  join pg_namespace namespace on namespace.oid = class.relnamespace
  where namespace.nspname = 'public'
    and class.relname = 'apartments'
    and attribute.attname = 'id'
    and not attribute.attisdropped;

  select format_type(attribute.atttypid, attribute.atttypmod)
  into booking_id_type
  from pg_attribute attribute
  join pg_class class on class.oid = attribute.attrelid
  join pg_namespace namespace on namespace.oid = class.relnamespace
  where namespace.nspname = 'public'
    and class.relname = 'bookings'
    and attribute.attname = 'id'
    and not attribute.attisdropped;

  if apartment_id_type is null then
    raise exception 'public.apartments.id was not found';
  end if;

  if booking_id_type is null then
    raise exception 'public.bookings.id was not found';
  end if;

  execute format(
    'create table if not exists public.favorites (
      id bigint generated by default as identity primary key,
      user_id uuid not null references auth.users(id) on delete cascade,
      apartment_id %s not null references public.apartments(id) on delete cascade,
      created_at timestamptz not null default now(),
      unique (user_id, apartment_id)
    )',
    apartment_id_type
  );

  execute format(
    'create table if not exists public.reviews (
      id bigint generated by default as identity primary key,
      user_id uuid not null references auth.users(id) on delete cascade,
      apartment_id %s not null references public.apartments(id) on delete cascade,
      rating int not null check (rating between 1 and 5),
      comment text,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      unique (user_id, apartment_id)
    )',
    apartment_id_type
  );

  execute format(
    'create table if not exists public.notifications (
      id bigint generated by default as identity primary key,
      user_id uuid not null references auth.users(id) on delete cascade,
      title text not null,
      message text not null,
      type text not null default ''info'',
      booking_id %s references public.bookings(id) on delete cascade,
      apartment_id %s references public.apartments(id) on delete cascade,
      read_at timestamptz,
      created_at timestamptz not null default now()
    )',
    booking_id_type,
    apartment_id_type
  );
end $$;

create index if not exists favorites_user_id_idx on public.favorites(user_id);
create index if not exists reviews_apartment_id_idx on public.reviews(apartment_id);
create index if not exists notifications_user_id_created_at_idx
  on public.notifications(user_id, created_at desc);

alter table public.favorites enable row level security;
alter table public.reviews enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "Users can manage own favorites" on public.favorites;
create policy "Users can manage own favorites"
on public.favorites
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Reviews are readable by authenticated users" on public.reviews;
create policy "Reviews are readable by authenticated users"
on public.reviews
for select
to authenticated
using (true);

drop policy if exists "Users can manage own reviews" on public.reviews;
create policy "Users can manage own reviews"
on public.reviews
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can read own notifications" on public.notifications;
create policy "Users can read own notifications"
on public.notifications
for select
using (auth.uid() = user_id);

drop policy if exists "Users can update own notifications" on public.notifications;
create policy "Users can update own notifications"
on public.notifications
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Authenticated users can create notifications" on public.notifications;
create policy "Authenticated users can create notifications"
on public.notifications
for insert
to authenticated
with check (true);
