-- RentFlow Sprint 2 schema.
-- Run after supabase_sprint1.sql in Supabase SQL Editor.

alter table public.apartments
  add column if not exists neighborhood text,
  add column if not exists address text,
  add column if not exists latitude double precision,
  add column if not exists longitude double precision,
  add column if not exists has_parking boolean not null default false,
  add column if not exists has_wifi boolean not null default false,
  add column if not exists pets_allowed boolean not null default false,
  add column if not exists is_furnished boolean not null default false,
  add column if not exists has_balcony boolean not null default false,
  add column if not exists has_elevator boolean not null default false,
  add column if not exists has_heating boolean not null default false;

alter table public.users
  add column if not exists verified boolean not null default false,
  add column if not exists verification_status text not null default 'unverified',
  add column if not exists identity_document_url text;

alter table public.bookings
  add column if not exists owner_id uuid references auth.users(id),
  add column if not exists status text not null default 'pending',
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancelled_by uuid references auth.users(id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'users_verification_status_check'
  ) then
    alter table public.users
      add constraint users_verification_status_check
      check (verification_status in ('unverified', 'pending', 'verified', 'rejected'));
  end if;
end $$;

do $$
declare
  apartment_id_type text;
begin
  select format_type(attribute.atttypid, attribute.atttypmod)
  into apartment_id_type
  from pg_attribute attribute
  join pg_class class on class.oid = attribute.attrelid
  join pg_namespace namespace on namespace.oid = class.relnamespace
  where namespace.nspname = 'public'
    and class.relname = 'apartments'
    and attribute.attname = 'id'
    and not attribute.attisdropped;

  if apartment_id_type is null then
    raise exception 'public.apartments.id was not found';
  end if;

  execute format(
    'create table if not exists public.conversations (
      id bigint generated by default as identity primary key,
      apartment_id %s not null references public.apartments(id) on delete cascade,
      owner_id uuid not null references auth.users(id) on delete cascade,
      client_id uuid not null references auth.users(id) on delete cascade,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      unique (apartment_id, owner_id, client_id)
    )',
    apartment_id_type
  );
end $$;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists apartments_city_price_rooms_idx
  on public.apartments(city, price, rooms);

create index if not exists apartments_amenities_idx
  on public.apartments(has_parking, has_wifi, pets_allowed, is_furnished, has_balcony, has_elevator, has_heating);

create index if not exists conversations_owner_updated_at_idx
  on public.conversations(owner_id, updated_at desc);

create index if not exists conversations_client_updated_at_idx
  on public.conversations(client_id, updated_at desc);

create index if not exists messages_conversation_created_at_idx
  on public.messages(conversation_id, created_at asc);

alter table public.conversations enable row level security;
alter table public.messages enable row level security;

grant select, insert, update on public.conversations to authenticated;
grant select, insert on public.messages to authenticated;
grant select, insert, update on public.notifications to authenticated;
grant select, insert, update on public.bookings to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception
  when duplicate_object then null;
end $$;

drop policy if exists "Authenticated users can create notifications" on public.notifications;
create policy "Authenticated users can create notifications"
on public.notifications
for insert
to authenticated
with check (true);

drop policy if exists "Booking members can read" on public.bookings;
create policy "Booking members can read"
on public.bookings
for select
using (
  auth.uid() = user_id
  or auth.uid() = owner_id
  or exists (
    select 1
    from public.apartments a
    where a.id = apartment_id
      and a.owner_id = auth.uid()
  )
);

drop policy if exists "Clients can create own bookings" on public.bookings;
create policy "Clients can create own bookings"
on public.bookings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Booking members can update status" on public.bookings;
create policy "Booking members can update status"
on public.bookings
for update
using (
  auth.uid() = user_id
  or auth.uid() = owner_id
  or exists (
    select 1
    from public.apartments a
    where a.id = apartment_id
      and a.owner_id = auth.uid()
  )
)
with check (
  auth.uid() = user_id
  or auth.uid() = owner_id
  or exists (
    select 1
    from public.apartments a
    where a.id = apartment_id
      and a.owner_id = auth.uid()
  )
);

drop policy if exists "Conversation members can read" on public.conversations;
create policy "Conversation members can read"
on public.conversations
for select
using (auth.uid() = owner_id or auth.uid() = client_id);

drop policy if exists "Clients can create owner conversations" on public.conversations;
create policy "Clients can create owner conversations"
on public.conversations
for insert
to authenticated
with check (auth.uid() = client_id or auth.uid() = owner_id);

drop policy if exists "Conversation members can update" on public.conversations;
create policy "Conversation members can update"
on public.conversations
for update
using (auth.uid() = owner_id or auth.uid() = client_id)
with check (auth.uid() = owner_id or auth.uid() = client_id);

drop policy if exists "Conversation members can read messages" on public.messages;
create policy "Conversation members can read messages"
on public.messages
for select
using (
  exists (
    select 1
    from public.conversations c
    where c.id = conversation_id
      and (c.owner_id = auth.uid() or c.client_id = auth.uid())
  )
);

drop policy if exists "Conversation members can send messages" on public.messages;
create policy "Conversation members can send messages"
on public.messages
for insert
to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1
    from public.conversations c
    where c.id = conversation_id
      and (c.owner_id = auth.uid() or c.client_id = auth.uid())
  )
);
